version: '3'
services:
  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - .:/test-app
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: dbclpm
      MYSQL_USER: duongpt
      MYSQL_PASSWORD: 123456
volumes:
  db_data: